"""
SciVizKit — Chart Registry
Central registry of all 50+ supported chart types.
"""

ALL_DOMAINS = ["General", "Biology", "Chemistry/Materials", "Medicine", "Physics", "Social Science"]

CHART_REGISTRY = {
    # ── Distribution ────────────────────────────────────────────────────
    "histogram": {
        "id": "histogram",
        "name": "Histogram",
        "category": "Distribution",
        "description": "Shows the frequency distribution of a single numeric variable.",
        "when_to_use": "Use when you want to understand the shape, spread, and central tendency of one variable.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "kde": {
        "id": "kde",
        "name": "KDE Plot",
        "category": "Distribution",
        "description": "Kernel Density Estimate — a smoothed version of the histogram.",
        "when_to_use": "Use to visualise the probability density of a continuous variable, especially for comparisons.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "violin": {
        "id": "violin",
        "name": "Violin Plot",
        "category": "Distribution",
        "description": "Combines box plot with KDE to show distribution shape per group.",
        "when_to_use": "Use when comparing distributions across multiple categories.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "boxplot": {
        "id": "boxplot",
        "name": "Box Plot",
        "category": "Distribution",
        "description": "Displays quartiles, median, and outliers of a distribution.",
        "when_to_use": "Use to compare summary statistics across groups and identify outliers.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "stripplot": {
        "id": "stripplot",
        "name": "Strip Plot",
        "category": "Distribution",
        "description": "Shows individual data points along an axis, optionally grouped.",
        "when_to_use": "Use with small-to-medium datasets to show all data points alongside group structure.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "beeswarm": {
        "id": "beeswarm",
        "name": "Beeswarm Plot",
        "category": "Distribution",
        "description": "Non-overlapping strip plot showing all individual points.",
        "when_to_use": "Use when you want to see every data point without overlap, especially for small datasets.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "ecdf": {
        "id": "ecdf",
        "name": "ECDF Plot",
        "category": "Distribution",
        "description": "Empirical Cumulative Distribution Function.",
        "when_to_use": "Use to understand what fraction of data falls below a given value.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "qqplot": {
        "id": "qqplot",
        "name": "Q-Q Plot",
        "category": "Distribution",
        "description": "Quantile-Quantile plot to assess normality of a distribution.",
        "when_to_use": "Use to check if your data follows a theoretical distribution (e.g., normal).",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },

    # ── Comparison ───────────────────────────────────────────────────────
    "bar": {
        "id": "bar",
        "name": "Bar Chart",
        "category": "Comparison",
        "description": "Compares values across discrete categories.",
        "when_to_use": "Use to compare magnitudes of different categories.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "grouped_bar": {
        "id": "grouped_bar",
        "name": "Grouped Bar Chart",
        "category": "Comparison",
        "description": "Side-by-side bars for comparing sub-groups within categories.",
        "when_to_use": "Use to compare values across categories broken down by a second variable.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 4},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "stacked_bar": {
        "id": "stacked_bar",
        "name": "Stacked Bar Chart",
        "category": "Comparison",
        "description": "Stacked bars showing part-to-whole relationships across categories.",
        "when_to_use": "Use to show composition within categories while comparing totals.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 4},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "lollipop": {
        "id": "lollipop",
        "name": "Lollipop Chart",
        "category": "Comparison",
        "description": "Cleaner alternative to bar chart with a line and dot.",
        "when_to_use": "Use when you have many categories and bar chart feels visually heavy.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "dumbbell": {
        "id": "dumbbell",
        "name": "Dumbbell Chart",
        "category": "Comparison",
        "description": "Shows change or difference between two values for each item.",
        "when_to_use": "Use to show before/after or two-condition comparisons per item.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "dotplot": {
        "id": "dotplot",
        "name": "Dot Plot",
        "category": "Comparison",
        "description": "Dots positioned along an axis for category comparisons.",
        "when_to_use": "Use as a cleaner alternative to a bar chart, especially with sorted data.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "slope": {
        "id": "slope",
        "name": "Slope Chart",
        "category": "Comparison",
        "description": "Shows change in rank or value between two time points.",
        "when_to_use": "Use to highlight change between exactly two points for multiple items.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "waterfall": {
        "id": "waterfall",
        "name": "Waterfall Chart",
        "category": "Comparison",
        "description": "Shows cumulative effect of sequential positive and negative values.",
        "when_to_use": "Use to visualise how an initial value changes step by step.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ["General", "Social Science", "Chemistry/Materials"],
        "static": True,
        "interactive": True,
    },
    "errorbar": {
        "id": "errorbar",
        "name": "Error Bar Plot",
        "category": "Comparison",
        "description": "Bar or point chart with error bars showing variability.",
        "when_to_use": "Use when you need to display measurement uncertainty or confidence intervals.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Correlation ───────────────────────────────────────────────────────
    "scatter": {
        "id": "scatter",
        "name": "Scatter Plot",
        "category": "Correlation",
        "description": "Two-dimensional relationship between two numeric variables.",
        "when_to_use": "Use to explore correlations and patterns between two continuous variables.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "bubble": {
        "id": "bubble",
        "name": "Bubble Chart",
        "category": "Correlation",
        "description": "Scatter plot with a third variable encoded as bubble size.",
        "when_to_use": "Use to show 3-4 variables simultaneously in a 2D plane.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "hexbin": {
        "id": "hexbin",
        "name": "Hexbin Plot",
        "category": "Correlation",
        "description": "Hexagonal binning for dense scatter plots.",
        "when_to_use": "Use when scatter plot has too many overlapping points (large datasets).",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 100},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "corr_heatmap": {
        "id": "corr_heatmap",
        "name": "Correlation Heatmap",
        "category": "Correlation",
        "description": "Matrix heatmap of Pearson correlation coefficients.",
        "when_to_use": "Use to quickly identify which variables are correlated in a multi-variable dataset.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "pairplot": {
        "id": "pairplot",
        "name": "Pair Plot",
        "category": "Correlation",
        "description": "Grid of scatter plots for all pairs of numeric variables.",
        "when_to_use": "Use for exploratory analysis of all pairwise relationships at once.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "parallel_coords": {
        "id": "parallel_coords",
        "name": "Parallel Coordinates",
        "category": "Correlation",
        "description": "Multi-axis plot for high-dimensional data relationships.",
        "when_to_use": "Use to detect patterns and clusters across many numeric dimensions simultaneously.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Time Series ───────────────────────────────────────────────────────
    "line": {
        "id": "line",
        "name": "Line Chart",
        "category": "Time Series",
        "description": "Classic line chart for time-ordered data.",
        "when_to_use": "Use to show trends or changes in a variable over time.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 1, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "area": {
        "id": "area",
        "name": "Area Chart",
        "category": "Time Series",
        "description": "Line chart with filled area below.",
        "when_to_use": "Use to emphasise cumulative totals or the magnitude of change over time.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 1, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "stacked_area": {
        "id": "stacked_area",
        "name": "Stacked Area Chart",
        "category": "Time Series",
        "description": "Multiple stacked area series showing composition over time.",
        "when_to_use": "Use to show how multiple variables contribute to a total over time.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 1, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "step_line": {
        "id": "step_line",
        "name": "Step Line Chart",
        "category": "Time Series",
        "description": "Step-function line chart for discrete change events.",
        "when_to_use": "Use for variables that change instantaneously (e.g., stock prices, dosage).",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 1, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Proportional ─────────────────────────────────────────────────────
    "pie": {
        "id": "pie",
        "name": "Pie Chart",
        "category": "Proportional",
        "description": "Classic circle divided into slices for part-to-whole.",
        "when_to_use": "Use sparingly, only when there are few categories and proportions differ markedly.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "donut": {
        "id": "donut",
        "name": "Donut Chart",
        "category": "Proportional",
        "description": "Pie chart with a hollow centre for labelling.",
        "when_to_use": "Use as a modern alternative to pie chart when the centre space is useful.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "treemap": {
        "id": "treemap",
        "name": "Treemap",
        "category": "Proportional",
        "description": "Hierarchical rectangles sized by value.",
        "when_to_use": "Use to show part-to-whole with many categories or hierarchical data.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "sunburst": {
        "id": "sunburst",
        "name": "Sunburst Chart",
        "category": "Proportional",
        "description": "Multi-level pie chart for hierarchical data.",
        "when_to_use": "Use for hierarchical part-to-whole data with two or more levels.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": False,
        "interactive": True,
    },
    "nightingale": {
        "id": "nightingale",
        "name": "Nightingale Rose Chart",
        "category": "Proportional",
        "description": "Polar bar chart (Florence Nightingale's coxcomb plot).",
        "when_to_use": "Use for cyclical or categorical data where polar representation adds clarity.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Network ───────────────────────────────────────────────────────────
    "sankey": {
        "id": "sankey",
        "name": "Sankey Diagram",
        "category": "Network",
        "description": "Flow diagram showing quantities between nodes.",
        "when_to_use": "Use to visualise flows, transfers, or conversions between categories.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": False,
        "interactive": True,
    },
    "network_graph": {
        "id": "network_graph",
        "name": "Network Graph",
        "category": "Network",
        "description": "Node-link diagram showing connections between entities.",
        "when_to_use": "Use to visualise relationships, edges, and network structure.",
        "requires": {"min_numeric": 0, "min_categorical": 2, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "dendrogram": {
        "id": "dendrogram",
        "name": "Dendrogram",
        "category": "Network",
        "description": "Hierarchical clustering tree diagram.",
        "when_to_use": "Use to show hierarchical clustering results of observations or features.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },

    # ── Scientific ────────────────────────────────────────────────────────
    "volcano": {
        "id": "volcano",
        "name": "Volcano Plot",
        "category": "Scientific",
        "description": "Log fold-change vs -log10(p-value) for differential expression.",
        "when_to_use": "Use in genomics/proteomics to show statistical significance vs magnitude of change.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ["Biology", "Medicine"],
        "static": True,
        "interactive": True,
    },
    "pca_plot": {
        "id": "pca_plot",
        "name": "PCA Plot",
        "category": "Scientific",
        "description": "Principal Component Analysis dimensionality reduction plot.",
        "when_to_use": "Use to visualise high-dimensional data in 2D and identify clusters.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "roc_curve": {
        "id": "roc_curve",
        "name": "ROC Curve",
        "category": "Scientific",
        "description": "Receiver Operating Characteristic curve for classifier evaluation.",
        "when_to_use": "Use to evaluate and compare binary classification model performance.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ["Medicine", "Biology", "General"],
        "static": True,
        "interactive": True,
    },
    "radar": {
        "id": "radar",
        "name": "Radar Chart",
        "category": "Scientific",
        "description": "Spider/web chart for multivariate comparison.",
        "when_to_use": "Use to compare items across multiple quantitative dimensions simultaneously.",
        "requires": {"min_numeric": 3, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "parity_plot": {
        "id": "parity_plot",
        "name": "Parity Plot",
        "category": "Scientific",
        "description": "Predicted vs actual values for model validation.",
        "when_to_use": "Use to assess how closely model predictions match experimental observations.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ["Chemistry/Materials", "Physics", "Medicine", "General"],
        "static": True,
        "interactive": True,
    },
    "bland_altman": {
        "id": "bland_altman",
        "name": "Bland-Altman Plot",
        "category": "Scientific",
        "description": "Agreement between two measurement methods.",
        "when_to_use": "Use to assess if two clinical or measurement methods agree sufficiently.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ["Medicine", "Biology", "General"],
        "static": True,
        "interactive": True,
    },
    "kaplan_meier": {
        "id": "kaplan_meier",
        "name": "Kaplan-Meier Curve",
        "category": "Scientific",
        "description": "Survival function estimator for time-to-event data.",
        "when_to_use": "Use for survival analysis: time-to-event outcomes in clinical or biological studies.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ["Medicine", "Biology"],
        "static": True,
        "interactive": True,
    },

    # ── Distribution (new) ───────────────────────────────────────────────
    "ridgeline": {
        "id": "ridgeline",
        "name": "Ridgeline / Joy Plot",
        "category": "Distribution",
        "description": "Overlapping KDE curves per group, offset vertically.",
        "when_to_use": "Compare distributions across many groups simultaneously.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 30},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "marginal_plot": {
        "id": "marginal_plot",
        "name": "Marginal Plot",
        "category": "Distribution",
        "description": "Scatter plot with marginal histograms on top and right axes.",
        "when_to_use": "Show joint distribution of two numeric variables along with their marginals.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "raincloud": {
        "id": "raincloud",
        "name": "Raincloud Plot",
        "category": "Distribution",
        "description": "Combined half-violin + box plot + jitter strip.",
        "when_to_use": "Show full data distribution richly: ideal for publication figures.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Comparison (new) ─────────────────────────────────────────────────
    "diverging_bar": {
        "id": "diverging_bar",
        "name": "Diverging Bar Chart",
        "category": "Comparison",
        "description": "Bars extend left and right from a central axis at zero.",
        "when_to_use": "Compare positive/negative values or deviations from a baseline.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "population_pyramid": {
        "id": "population_pyramid",
        "name": "Population Pyramid",
        "category": "Comparison",
        "description": "Back-to-back horizontal bars comparing two groups (e.g., male/female).",
        "when_to_use": "Compare two distributions across categories (age groups, demographics).",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 5},
        "domains": ["General", "Medicine", "Social Science"],
        "static": True,
        "interactive": True,
    },
    "percent_stacked_bar": {
        "id": "percent_stacked_bar",
        "name": "100% Stacked Bar",
        "category": "Comparison",
        "description": "Stacked bars normalized to 100% showing relative proportions.",
        "when_to_use": "Compare part-to-whole proportions across multiple groups.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "radial_bar": {
        "id": "radial_bar",
        "name": "Radial Bar Chart",
        "category": "Comparison",
        "description": "Bar chart wrapped around a circular polar axis.",
        "when_to_use": "Visually engaging comparison of categories — best for presentations.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "bullet_chart": {
        "id": "bullet_chart",
        "name": "Bullet Chart",
        "category": "Comparison",
        "description": "Shows actual value vs target with qualitative ranges.",
        "when_to_use": "Compare performance against targets or benchmarks.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 1},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "tornado_chart": {
        "id": "tornado_chart",
        "name": "Tornado Chart",
        "category": "Comparison",
        "description": "Horizontal diverging bars sorted by range — sensitivity analysis.",
        "when_to_use": "Show which variables have the most impact in sensitivity analysis.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ["General", "Physics", "Chemistry/Materials"],
        "static": True,
        "interactive": True,
    },

    # ── Correlation (new) ─────────────────────────────────────────────────
    "contour_2d": {
        "id": "contour_2d",
        "name": "2D KDE Contour",
        "category": "Correlation",
        "description": "Contour lines showing density of two numeric variables.",
        "when_to_use": "Visualize joint density of two continuous variables with many data points.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 50},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "connected_scatter": {
        "id": "connected_scatter",
        "name": "Connected Scatter",
        "category": "Correlation",
        "description": "Scatter plot where points are connected by lines showing trajectory.",
        "when_to_use": "Show evolution of two variables over time or sequential order.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "marginal_scatter": {
        "id": "marginal_scatter",
        "name": "Marginal Scatter",
        "category": "Correlation",
        "description": "Scatter with KDE marginal distributions on axes.",
        "when_to_use": "Show relationship between two variables plus their individual distributions.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Time Series (new) ─────────────────────────────────────────────────
    "streamgraph": {
        "id": "streamgraph",
        "name": "Streamgraph",
        "category": "Time Series",
        "description": "Stacked area chart centered at zero for organic flow.",
        "when_to_use": "Show how multiple categories change over time with aesthetic flow.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "bump_chart": {
        "id": "bump_chart",
        "name": "Bump Chart",
        "category": "Time Series",
        "description": "Ranking chart showing how positions change over time.",
        "when_to_use": "Track rank changes of multiple items over time.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "calendar_heatmap": {
        "id": "calendar_heatmap",
        "name": "Calendar Heatmap",
        "category": "Time Series",
        "description": "GitHub-style heatmap showing daily values in a calendar grid.",
        "when_to_use": "Reveal seasonal patterns or daily activity over months/years.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 1, "min_rows": 30},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "candlestick": {
        "id": "candlestick",
        "name": "Candlestick Chart",
        "category": "Time Series",
        "description": "OHLC chart showing open, high, low, close values per period.",
        "when_to_use": "Visualize financial or experimental data with open/close/high/low per timepoint.",
        "requires": {"min_numeric": 4, "min_categorical": 0, "min_datetime": 1, "min_rows": 10},
        "domains": ["General", "Physics"],
        "static": False,
        "interactive": True,
    },
    "spiral_chart": {
        "id": "spiral_chart",
        "name": "Spiral Chart",
        "category": "Time Series",
        "description": "Polar time series winding outward, revealing cyclic patterns.",
        "when_to_use": "Show cyclical/seasonal patterns in long time series data.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 1, "min_rows": 30},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },

    # ── Proportional (new) ────────────────────────────────────────────────
    "waffle": {
        "id": "waffle",
        "name": "Waffle Chart",
        "category": "Proportional",
        "description": "10x10 grid of squares colored by category proportion.",
        "when_to_use": "Show part-to-whole relationships in an engaging, easy-to-read format.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "marimekko": {
        "id": "marimekko",
        "name": "Marimekko Chart",
        "category": "Proportional",
        "description": "Mosaic chart where both bar width and height encode data.",
        "when_to_use": "Show two categorical dimensions simultaneously with proportional areas.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 4},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "circle_packing": {
        "id": "circle_packing",
        "name": "Circle Packing",
        "category": "Proportional",
        "description": "Nested circles where size encodes value.",
        "when_to_use": "Show hierarchical or flat proportional data in a compact circular layout.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": False,
        "interactive": True,
    },

    # ── Network (new) ─────────────────────────────────────────────────────
    "chord_diagram": {
        "id": "chord_diagram",
        "name": "Chord Diagram",
        "category": "Network",
        "description": "Circular diagram showing flows or connections between entities.",
        "when_to_use": "Show bidirectional flows or relationships between multiple categories.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "arc_diagram": {
        "id": "arc_diagram",
        "name": "Arc Diagram",
        "category": "Network",
        "description": "Nodes on a line connected by semicircular arcs.",
        "when_to_use": "Show connections between items arranged linearly.",
        "requires": {"min_numeric": 0, "min_categorical": 2, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "alluvial": {
        "id": "alluvial",
        "name": "Alluvial Diagram",
        "category": "Network",
        "description": "Multi-stage flow diagram showing transitions between categories.",
        "when_to_use": "Show how populations flow between categories at multiple timepoints.",
        "requires": {"min_numeric": 0, "min_categorical": 2, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": False,
        "interactive": True,
    },

    # ── Text ──────────────────────────────────────────────────────────────
    "wordcloud": {
        "id": "wordcloud",
        "name": "Word Cloud",
        "category": "Text",
        "description": "Visual representation of word frequencies from text data.",
        "when_to_use": "Explore most frequent terms in a text column.",
        "requires": {"min_numeric": 0, "min_categorical": 1, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "venn": {
        "id": "venn",
        "name": "Venn Diagram",
        "category": "Text",
        "description": "Overlapping circles showing set intersections.",
        "when_to_use": "Show overlap between 2-3 groups or categories.",
        "requires": {"min_numeric": 0, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },

    # ── Geographic ────────────────────────────────────────────────────────
    "choropleth": {
        "id": "choropleth",
        "name": "Choropleth Map",
        "category": "Geographic",
        "description": "World/country map colored by a numeric variable.",
        "when_to_use": "Show geographic distribution of a variable across regions.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ["General", "Social Science", "Medicine"],
        "static": False,
        "interactive": True,
    },
    "bubble_map": {
        "id": "bubble_map",
        "name": "Bubble Map",
        "category": "Geographic",
        "description": "Map with circles sized by a numeric variable at lat/lon coordinates.",
        "when_to_use": "Show geographic data with quantity encoded as bubble size.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 3},
        "domains": ["General", "Social Science", "Medicine"],
        "static": False,
        "interactive": True,
    },

    # ── Scientific (new) ──────────────────────────────────────────────────
    "umap_plot": {
        "id": "umap_plot",
        "name": "UMAP Plot",
        "category": "Scientific",
        "description": "Non-linear dimensionality reduction preserving local structure.",
        "when_to_use": "Explore high-dimensional data clusters; alternative to t-SNE.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ["Biology", "Chemistry/Materials", "General"],
        "static": True,
        "interactive": True,
    },
    "tsne_plot": {
        "id": "tsne_plot",
        "name": "t-SNE Plot",
        "category": "Scientific",
        "description": "t-distributed stochastic neighbor embedding for dimensionality reduction.",
        "when_to_use": "Visualize high-dimensional data clusters in 2D.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ["Biology", "Chemistry/Materials", "General"],
        "static": True,
        "interactive": True,
    },
    "manhattan_plot": {
        "id": "manhattan_plot",
        "name": "Manhattan Plot",
        "category": "Scientific",
        "description": "Genome-wide significance plot: chromosomal position vs -log10(p-value).",
        "when_to_use": "GWAS or genomic association studies to identify significant loci.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 100},
        "domains": ["Biology", "Medicine"],
        "static": True,
        "interactive": True,
    },
    "forest_plot": {
        "id": "forest_plot",
        "name": "Forest Plot",
        "category": "Scientific",
        "description": "Meta-analysis plot showing effect sizes with confidence intervals.",
        "when_to_use": "Summarize results from multiple studies in systematic reviews.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ["Medicine", "Biology"],
        "static": True,
        "interactive": True,
    },
    "funnel_plot": {
        "id": "funnel_plot",
        "name": "Funnel Plot",
        "category": "Scientific",
        "description": "Effect size vs precision to detect publication bias.",
        "when_to_use": "Check for publication bias in meta-analysis.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 5},
        "domains": ["Medicine", "Biology"],
        "static": True,
        "interactive": True,
    },
    "calibration_curve": {
        "id": "calibration_curve",
        "name": "Calibration Curve",
        "category": "Scientific",
        "description": "Predicted probability vs observed frequency for classifier reliability.",
        "when_to_use": "Evaluate how well a probability model is calibrated.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ["Medicine", "Biology", "General"],
        "static": True,
        "interactive": True,
    },
    "residual_plot": {
        "id": "residual_plot",
        "name": "Residual Plot",
        "category": "Scientific",
        "description": "Fitted values vs residuals for regression diagnostics.",
        "when_to_use": "Check model assumptions: detect heteroscedasticity and outliers.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "upset_plot": {
        "id": "upset_plot",
        "name": "UpSet Plot",
        "category": "Scientific",
        "description": "Alternative to Venn for visualizing set intersections with many sets.",
        "when_to_use": "Compare overlaps between more than 3 groups or binary feature sets.",
        "requires": {"min_numeric": 0, "min_categorical": 3, "min_datetime": 0, "min_rows": 10},
        "domains": ["Biology", "Medicine", "General"],
        "static": True,
        "interactive": False,
    },

    # ── 3D ────────────────────────────────────────────────────────────────
    "scatter_3d": {
        "id": "scatter_3d",
        "name": "3D Scatter Plot",
        "category": "3D",
        "description": "Three-dimensional scatter plot for exploring 3-variable relationships.",
        "when_to_use": "Visualize relationships among three continuous variables simultaneously.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": False,
        "interactive": True,
    },
    "surface_3d": {
        "id": "surface_3d",
        "name": "3D Surface Plot",
        "category": "3D",
        "description": "Continuous surface over a 2D grid of x and y values.",
        "when_to_use": "Visualize a mathematical function or response surface over a 2D parameter space.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ["Physics", "Chemistry/Materials", "General"],
        "static": False,
        "interactive": True,
    },
    "bar_3d": {
        "id": "bar_3d",
        "name": "3D Bar Chart",
        "category": "3D",
        "description": "Bars extruded in 3D space across two categorical axes.",
        "when_to_use": "Compare values across two categorical dimensions with a striking 3D visual.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 4},
        "domains": ALL_DOMAINS,
        "static": False,
        "interactive": True,
    },

    # ── NGplot-inspired (bioinforw.com/sciZ) ────────────────────────────
    "jade_ring": {
        "id": "jade_ring",
        "name": "Jade Ring Chart",
        "name_zh": "玉珏图",
        "category": "Proportional",
        "description": "Concentric arc rings where each ring represents a group and arc length encodes its value. A signature bioinformatics chart from NGplot.",
        "when_to_use": "Use to compare relative magnitudes across multiple groups with an elegant circular layout. Popular in biology for sample-level abundance comparisons.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ["Biology", "Medicine", "General"],
        "static": True,
        "interactive": False,
    },
    "bar_sig": {
        "id": "bar_sig",
        "name": "Bar + Significance",
        "name_zh": "星号连接柱状图",
        "category": "Comparison",
        "description": "Bar chart with error bars and pairwise significance brackets (Mann-Whitney U). Inspired by NGplot's most popular 星号连接 templates.",
        "when_to_use": "Use when comparing groups and you need statistical significance annotations — the standard for biology/medicine publications.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 6},
        "domains": ["Biology", "Medicine", "General", "Social Science"],
        "static": True,
        "interactive": False,
    },
    "radial_bar_sig": {
        "id": "radial_bar_sig",
        "name": "Radial Bar + Significance",
        "name_zh": "环形柱状图+误差线",
        "category": "Scientific",
        "description": "Polar bar chart with SEM error bars and one-way ANOVA annotation. Inspired by NGplot's 环形柱状图-多变量-误差线-星号连接 templates.",
        "when_to_use": "Use to compare groups in a visually striking radial layout with error bars — common in multi-group biological experiments.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 6},
        "domains": ["Biology", "Medicine", "Chemistry/Materials", "Physics"],
        "static": True,
        "interactive": False,
    },
}
